### ISSUE TITLE
Issues when building the pdf

### ISSUE THREAD

**Issue by Syntax3rror404** [markushaug/iu-wissdoc-template#2] opened 2023-12-09 16:59 UTC
Using latest version of TeX Live

Getting this errors and a broken pdf

Used command: `lualatex main`

```
! LaTeX Error: Option clash for package csquotes.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.82 \usepackage
              [backend=biber, style=apa, pagetracker, ibidtracker=constrict,...
```

```
! LaTeX Error: Option clash for package biblatex.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.83
```

```
No file main.aux.
(c:/texlive/2023/texmf-dist/tex/latex/base/ts1cmr.fd)
*geometry* driver: auto-detecting
*geometry* detected driver: luatex
(c:/texlive/2023/texmf-dist/tex/context/base/mkii/supp-pdf.mkii
[Loading MPS to PDF converter (version 2006.09.02).]
) (c:/texlive/2023/texmf-dist/tex/latex/epstopdf-pkg/epstopdf-base.sty
(c:/texlive/2023/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg))
(c:/texlive/2023/texmf-dist/tex/latex/biblatex-apa/ngerman-apa.lbx
(c:/texlive/2023/texmf-dist/tex/latex/biblatex/lbx/ngerman.lbx
(c:/texlive/2023/texmf-dist/tex/latex/biblatex-apa/german-apa.lbx
(c:/texlive/2023/texmf-dist/tex/latex/biblatex/lbx/german.lbx)))
(c:/texlive/2023/texmf-dist/tex/latex/biblatex/lbx/ngerman.lbx
(c:/texlive/2023/texmf-dist/tex/latex/biblatex-apa/german-apa.lbx
(c:/texlive/2023/texmf-dist/tex/latex/biblatex/lbx/german.lbx)))) (./main.bbl)
(./pages/cover.tex [1{c:/texlive/2023/texmf-var/fonts/map/pdftex/updmap/pdftex.
map}<./logos/IU.png>])
No file main.toc.

warning  (pdf backend): ignoring duplicate destination with the name 'page.'
[1]
No file main.lof.

warning  (pdf backend): ignoring duplicate destination with the name 'page.'
[2]
warning  (pdf backend): ignoring duplicate destination with the name 'page.'
[3] (./chapters/einleitung.tex)
(c:/texlive/2023/texmf-dist/tex/generic/hyph-utf8/loadhyph/loadhyph-la.tex
UTF-8 Latin hyphenation patterns
(c:/texlive/2023/texmf-dist/tex/generic/hyph-utf8/patterns/tex/hyph-la.tex))
[1] (./chapters/hauptteil.tex

LaTeX Warning: Reference `fig:logo_iu' on page 2 undefined on input line 17.


LaTeX Warning: Reference `pos:logo_iu' on page 2 undefined on input line 17.


Package acronym Warning: Acronym `iu' is not defined on input line 17.


Package acronym Warning: Acronym `iu' is not defined on input line 17.


Package acronym Warning: Acronym `iu' is not defined on input line 22.

) [2] (./chapters/schluss.tex) [3]
warning  (pdf backend): ignoring duplicate destination with the name 'page.'
[1] (./pages/appendix.tex)
warning  (pdf backend): ignoring duplicate destination with the name 'page.'
[2] (./main.aux (./pages/cover.aux) (./chapters/einleitung.aux)
(./chapters/hauptteil.aux) (./chapters/schluss.aux) (./pages/appendix.aux))

LaTeX Warning: There were undefined references.


LaTeX Warning: Label(s) may have changed. Rerun to get cross-references right.


Package rerunfilecheck Warning: File `main.out' has changed.
(rerunfilecheck)                Rerun to get outlines right
(rerunfilecheck)                or use package `bookmark'.


Package biblatex Warning: Please (re)run Biber on the file:
(biblatex)                main
(biblatex)                and rerun LaTeX afterwards.

)
 707 words of node memory still in use:
   5 hlist, 1 vlist, 1 rule, 2 disc, 6 glue, 4 kern, 18 glyph, 14 attribute, 63
 glue_spec, 8 attribute_list, 3 write nodes
   avail lists: 1:1,2:685,3:176,4:30,5:98,6:33,7:6539,8:76,9:190,10:22,11:658
<c:/texlive/2023/texmf-dist/fonts/opentype/public/lm/lmmono10-regular.otf><c:/W
indows/Fonts/ariali.ttf><c:/Windows/Fonts/arial.ttf><c:/Windows/Fonts/arialbd.t
tf>
Output written on main.pdf (9 pages, 102622 bytes).
Transcript written on main.log.
```

**Comment by LostInTh3N3wR3al** [comment] 2024-01-11 09:36
I deleted the lines 61-75 in main.tex. They are a duplicate of the lines below. After that I did not get any error.

**Comment by Syntax3rror404** [comment] 2024-01-11 19:21
Thank you :) But this doesnt helped :/

**Comment by markushaug** [comment] 2024-01-12 20:07
Hey, could you please share more details of your environment?

**Comment by markushaug** [comment] 2024-01-12 20:34
> I deleted the lines 61-75 in main.tex. They are a duplicate of the lines below. After that I did not get any error.

I investigated a bit on it. Seems like I forget to take the old ones out. Thanks! I have updated the repo.

**Comment by markushaug** [comment] 2024-01-12 20:37
Update: After taking the lines out, I was able to generate the PDF without any issues. Could you please try to clone again and try to build it?

My Version: LuaHBTeX, Version 1.15.0 (TeX Live 2022)

**Comment by Syntax3rror404** [comment] 2024-01-13 02:43
I use Tex Live 2023.

Yes I tried again with the same issues again :(

**Comment by Syntax3rror404** [comment] 2024-01-13 02:47
I use latest Texlive 2023

**Comment by Syntax3rror404** [comment] 2024-01-13 02:48
Oh ... now the pdf looks fine and i get code 0 so no error.

This is fine?

![image](https://github.com/markushaug/iu-wissdoc-template/assets/57288415/1ce04725-86d8-47ff-864d-741e3db27e67)

**Comment by Syntax3rror404** [comment] 2024-01-13 02:56
Ok there are now problems with the table of contents.

![image](https://github.com/markushaug/iu-wissdoc-template/assets/57288415/f4075fcc-4ab7-4e7d-bd8a-04e6d19a6157)

After execute biber main I the only left warning is `inputenc package ignored with utf8 based engines`

**Comment by markushaug** [comment] 2024-01-14 12:15
I haven't tried it on TexLive 23 yet. You can ignore the warnings for the time being. 

What are your issues with the TOC?

**Comment by Syntax3rror404** [comment] 2024-01-14 14:45
As you can see in the picture the roman symbols are missing

**Comment by markushaug** [comment] 2024-01-14 17:02
Please refer to the current version of the official IU guide for case studies ("[Prüfungsleitfaden Fallstudie](https://mycampus.iubh.de/mod/resource/view.php?id=188387&redirect=1)"). There you can find that only the respective in-text chapters shall be numbered. All other parts such as the bibliography, list of figures, etc. shall not be numbered.

**Comment by markushaug** [comment] 2024-01-14 17:47
True.. I have added them 😊 

Let me know once you find another issue in the template. I'm happy to help.

**Comment by Syntax3rror404** [comment] 2024-01-14 17:56
@markushaug thank you for your help!! Now everything looks fine :)

Are the IU form standarts up to date? I ask because this repo is a little bit older :D 
Its hard for me to check this, I'm a latex newbie

**Comment by markushaug** [comment] 2024-01-14 18:13
You're welcome :) 

I'm still a student, and I'm using the template for the case study I'm currently composing. Therefore, all information known to me has been taken into account to reflect all requirements for the formalities as well as for the bibliography standard (But please respect my disclaimer).

Section 2.3 of the official case study guide ("[Prüfungsleitfaden Fallstudie](https://mycampus.iubh.de/pluginfile.php/325393/mod_resource/content/8/Pr%C3%BCfungsleitfaden%20Fallstudie.pdf?forcedownload=1)") entails all the current regulations.

The guide also says that numbering the list of figures shall not be conducted. However, I prefer to refer to figure numbers in my text. Therefore, I'm also numbering the list of figures (I never had any issues with that in my previous case studies for IU).

**Closed as completed** 2024-01-14 18:17 UTC
